package com.istl.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

import com.istl.app.domain.mobileapp.Channels;

public class ChannelsAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertChannelsAllPropertiesEquals(Channels expected, Channels actual) {
        assertChannelsAutoGeneratedPropertiesEquals(expected, actual);
        assertChannelsAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertChannelsAllUpdatablePropertiesEquals(Channels expected, Channels actual) {
        assertChannelsUpdatableFieldsEquals(expected, actual);
        assertChannelsUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertChannelsAutoGeneratedPropertiesEquals(Channels expected, Channels actual) {
        assertThat(expected)
            .as("Verify Channels auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertChannelsUpdatableFieldsEquals(Channels expected, Channels actual) {
        assertThat(expected)
            .as("Verify Channels relevant properties")
            .satisfies(e -> assertThat(e.getChannel()).as("check channel").isEqualTo(actual.getChannel()))
            .satisfies(e -> assertThat(e.getDescription()).as("check description").isEqualTo(actual.getDescription()))
            .satisfies(e -> assertThat(e.getBin()).as("check bin").isEqualTo(actual.getBin()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertChannelsUpdatableRelationshipsEquals(Channels expected, Channels actual) {
        // empty method
    }
}
