package com.istl.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CHANNELSAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCHANNELSAllPropertiesEquals(CHANNELS expected, CHANNELS actual) {
        assertCHANNELSAutoGeneratedPropertiesEquals(expected, actual);
        assertCHANNELSAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCHANNELSAllUpdatablePropertiesEquals(CHANNELS expected, CHANNELS actual) {
        assertCHANNELSUpdatableFieldsEquals(expected, actual);
        assertCHANNELSUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCHANNELSAutoGeneratedPropertiesEquals(CHANNELS expected, CHANNELS actual) {
        assertThat(expected)
            .as("Verify CHANNELS auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCHANNELSUpdatableFieldsEquals(CHANNELS expected, CHANNELS actual) {
        assertThat(expected)
            .as("Verify CHANNELS relevant properties")
            .satisfies(e -> assertThat(e.getcHANNEL()).as("check cHANNEL").isEqualTo(actual.getcHANNEL()))
            .satisfies(e -> assertThat(e.getdESCRIPTION()).as("check dESCRIPTION").isEqualTo(actual.getdESCRIPTION()))
            .satisfies(e -> assertThat(e.getbIN()).as("check bIN").isEqualTo(actual.getbIN()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCHANNELSUpdatableRelationshipsEquals(CHANNELS expected, CHANNELS actual) {
        // empty method
    }
}
