package com.istl.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class MESSAGETEMPLATESAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMESSAGETEMPLATESAllPropertiesEquals(MESSAGETEMPLATES expected, MESSAGETEMPLATES actual) {
        assertMESSAGETEMPLATESAutoGeneratedPropertiesEquals(expected, actual);
        assertMESSAGETEMPLATESAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMESSAGETEMPLATESAllUpdatablePropertiesEquals(MESSAGETEMPLATES expected, MESSAGETEMPLATES actual) {
        assertMESSAGETEMPLATESUpdatableFieldsEquals(expected, actual);
        assertMESSAGETEMPLATESUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMESSAGETEMPLATESAutoGeneratedPropertiesEquals(MESSAGETEMPLATES expected, MESSAGETEMPLATES actual) {
        assertThat(expected)
            .as("Verify MESSAGETEMPLATES auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMESSAGETEMPLATESUpdatableFieldsEquals(MESSAGETEMPLATES expected, MESSAGETEMPLATES actual) {
        assertThat(expected)
            .as("Verify MESSAGETEMPLATES relevant properties")
            .satisfies(e -> assertThat(e.getmESSAGETYPE()).as("check mESSAGETYPE").isEqualTo(actual.getmESSAGETYPE()))
            .satisfies(e -> assertThat(e.getdESCRIPTION()).as("check dESCRIPTION").isEqualTo(actual.getdESCRIPTION()))
            .satisfies(e -> assertThat(e.getmESSAGEENGLISH()).as("check mESSAGEENGLISH").isEqualTo(actual.getmESSAGEENGLISH()))
            .satisfies(e -> assertThat(e.getmESSAGESOMALI()).as("check mESSAGESOMALI").isEqualTo(actual.getmESSAGESOMALI()))
            .satisfies(e -> assertThat(e.getcREATEDON()).as("check cREATEDON").isEqualTo(actual.getcREATEDON()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMESSAGETEMPLATESUpdatableRelationshipsEquals(MESSAGETEMPLATES expected, MESSAGETEMPLATES actual) {
        // empty method
    }
}
