package com.istl.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

import com.istl.app.domain.mobileapp.MobileAppTransactions;

public class MobileAppTransactionsAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMobileAppTransactionsAllPropertiesEquals(MobileAppTransactions expected, MobileAppTransactions actual) {
        assertMobileAppTransactionsAutoGeneratedPropertiesEquals(expected, actual);
        assertMobileAppTransactionsAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMobileAppTransactionsAllUpdatablePropertiesEquals(
        MobileAppTransactions expected,
        MobileAppTransactions actual
    ) {
        assertMobileAppTransactionsUpdatableFieldsEquals(expected, actual);
        assertMobileAppTransactionsUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMobileAppTransactionsAutoGeneratedPropertiesEquals(
        MobileAppTransactions expected,
        MobileAppTransactions actual
    ) {
        assertThat(expected)
            .as("Verify MobileAppTransactions auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMobileAppTransactionsUpdatableFieldsEquals(MobileAppTransactions expected, MobileAppTransactions actual) {
        assertThat(expected)
            .as("Verify MobileAppTransactions relevant properties")
            .satisfies(e -> assertThat(e.getChannel()).as("check channel").isEqualTo(actual.getChannel()))
            .satisfies(e -> assertThat(e.getChannelIp()).as("check channelIp").isEqualTo(actual.getChannelIp()))
            .satisfies(e -> assertThat(e.getChannelReference()).as("check channelReference").isEqualTo(actual.getChannelReference()))
            .satisfies(e -> assertThat(e.getChannelTimestamp()).as("check channelTimestamp").isEqualTo(actual.getChannelTimestamp()))
            .satisfies(e -> assertThat(e.getClientId()).as("check clientId").isEqualTo(actual.getClientId()))
            .satisfies(e -> assertThat(e.getCreatedAt()).as("check createdAt").isEqualTo(actual.getCreatedAt()))
            .satisfies(e -> assertThat(e.getDebitAccount()).as("check debitAccount").isEqualTo(actual.getDebitAccount()))
            .satisfies(e -> assertThat(e.getDirection()).as("check direction").isEqualTo(actual.getDirection()))
            .satisfies(e -> assertThat(e.getErrorDescription()).as("check errorDescription").isEqualTo(actual.getErrorDescription()))
            .satisfies(e -> assertThat(e.getGeolocation()).as("check geolocation").isEqualTo(actual.getGeolocation()))
            .satisfies(e -> assertThat(e.getHostCode()).as("check hostCode").isEqualTo(actual.getHostCode()))
            .satisfies(e -> assertThat(e.getPhoneNumber()).as("check phoneNumber").isEqualTo(actual.getPhoneNumber()))
            .satisfies(e -> assertThat(e.getResponseCode()).as("check responseCode").isEqualTo(actual.getResponseCode()))
            .satisfies(e -> assertThat(e.getResponseMessage()).as("check responseMessage").isEqualTo(actual.getResponseMessage()))
            .satisfies(e -> assertThat(e.getTransactionCode()).as("check transactionCode").isEqualTo(actual.getTransactionCode()))
            .satisfies(e -> assertThat(e.getTransactionType()).as("check transactionType").isEqualTo(actual.getTransactionType()))
            .satisfies(e -> assertThat(e.getUserAgent()).as("check userAgent").isEqualTo(actual.getUserAgent()))
            .satisfies(e -> assertThat(e.getUserAgentVersion()).as("check userAgentVersion").isEqualTo(actual.getUserAgentVersion()))
            .satisfies(e -> assertThat(e.getAmount()).as("check amount").isEqualTo(actual.getAmount()))
            .satisfies(e -> assertThat(e.getChargeamount()).as("check chargeamount").isEqualTo(actual.getChargeamount()))
            .satisfies(e -> assertThat(e.getCreditAccount()).as("check creditAccount").isEqualTo(actual.getCreditAccount()))
            .satisfies(e -> assertThat(e.getCbsReference()).as("check cbsReference").isEqualTo(actual.getCbsReference()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMobileAppTransactionsUpdatableRelationshipsEquals(
        MobileAppTransactions expected,
        MobileAppTransactions actual
    ) {
        // empty method
    }
}
